# Generated by Django 6.0.3 on 2026-04-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='encrypted_gemini_key',
            field=models.TextField(blank=True, default=''),
        ),
    ]
