# Generated by Django 6.0.3 on 2026-04-19 11:45

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_encrypted_gemini_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitetoken',
            name='expires_at',
            field=models.DateTimeField(default=projects.models._default_invite_expiry),
        ),
    ]
